### ISSUE TITLE
encoding problem for subject

### ISSUE THREAD

**Issue by fcabaud** [maxtepkeev/python-redmine#104]
I'm with python 3.4 on Windows.

When I read an Issue via the folowing code, the tittle is wrong 
  key = "blablabla"
  config = {'key': key, 'server': 'https://myserver'}
  red = redmine("myproject", config)
  red._connect("project", config)
  issueObj = red.issue.get(12345)
  print(issueObj.subject.name)

The correct subject on redmine (see on Chrome or Firefox) is 
MyTV b? Pe

I got via the redmine module
MyTV b?\x13 Pe

Please, what can I do for having the correct subject ?

**Comment by maxtepkeev** [comment]
Hi,

It's had to say exactly, because I don't have access to your Redmine, but...

If I'm not mistaked \x13 is a carriage return in ASCII (\r) so you probably have it in your subject field, and you can't see it because it's a special character, like newline, for example, but because python-redmine is a program, it sees it and shows it to you.

So as far as I can tell, there is nothing wrong with python-redmine's behaviour here, just go to your Redmine interface and retype the subject by hand if you can, if not, remove this symbol in your code.

**Comment by fcabaud** [comment]
Exactly 
I dont know how this character cames here.
Thank you very much.
