### ISSUE TITLE
Add tests directory to source tarball

### ISSUE THREAD

**Issue by bdrung** [maxtepkeev/python-redmine#108]
Please add the tests directory to source tarball, since we use that for the Debian package. Otherwise the tests cannot be run from the source tarball.

**Comment by maxtepkeev** [comment]
Hi Benjamin,

You mean the tarball which you get from PyPI, like [this one](https://pypi.python.org/packages/source/p/python-redmine/python-redmine-1.2.0.tar.gz) for v 1.2.0 ?

**Comment by bdrung** [comment]
Yes, exactly.

**Comment by maxtepkeev** [comment]
Done.

You can now also use python setup.py test command which will figure out all the dependencies needed for running tests on the current system and after installing them if they are not here it will run the tests.

Also starting from v1.4.0 requests are now bundled with Python-Redmine and will be updated as needed. That will make package much more stable.

Let me know if everything works for you as it should.

**Comment by bdrung** [comment]
Please do not bundle needed libraries into your package. The Debian package will always use python-request from the system. Bundled libraries have the drawback that they increases the source package size and that I have to document also their license.

See also https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code

**Comment by maxtepkeev** [comment]
I'm sorry but I fully disagree.

1) Python-Redmine uses relative imports which means that it will always use the bundled Requests library and not the one from the system or from virtualenv or another one installed elsewhere.
2) The size of the package increased by a few hundred kilobytes which is nothing in the current world of terabytes.
3) The license of the bundled package is already included with Python-Redmine (see NOTICE).

Python-Redmine exists for more than 1.5 years now and I had several bug reports connected with the wrong Requests library version on the system, which was very hard to identify. Also, a lot of packages bundle other packages and that is a fact of life, because bundling makes the developer life easier and it also provides users of the package with the best possible experience. For example take the Requests library, it bundles ``chardet`` and ``urllib3`` packages, and ``urllib3`` also bundles ``ordered_dict``, ``six`` and ``ssl_match_hostname`` packages. There was already the same discussion about the Requests library, you can see it [here](https://github.com/kennethreitz/requests/pull/1812), I agree with everything that was said in there so I'm not going to repeat the same things.

I really appreciate your work for making Python-Redmine available in Debian and Ubuntu, but bundling libraries makes life better, not worse, that is why I'm not going to change my mind about this.

**Comment by maxtepkeev** [comment]
@bdrung There is an ongoing discussion in the #109 about whether it was a good idea to bundle ``python-requests`` and I have a proposal to make everybody happy, I would appreciate to hear your thoughts about it in the #109. Thanks.

I'm closing this issue because it is related to tests and we figured everything about them already.
