### ISSUE TITLE
In operator not working on resource objects

### ISSUE THREAD

**Issue by Boldie** [maxtepkeev/python-redmine#111]
The in operator is not working, it just returns False every time.

    >>> i=rm.issue.get(1)
    >>> dir(i)
    [u'assigned_to', 'attachments', u'author', 'changesets', 'children', u'closed_on', u'created_on', u'description', u'done_ratio', u'fixed_version', u'id', 'journals', u'parent', u'priority', u'project', 'relations', u'start_date', u'status', u'subject', 'time_entries', u'tracker', u'updated_on', 'watchers']
    >>> 'id' in i
    False

This is useful, for e.g. while dealing with journals because not every journal has a notes attribute attached and thus for the moment one has to write:

    if 'notes' in dir(journal):

I am unsure why it does not work.

**Comment by maxtepkeev** [comment]
There's no reason why it should work. ``in`` in Python is used to check if an item is available in an iterable data structure and a resource object isn't that kind of data structure by design. You need to use ``hasattr`` or ``getattr`` with default value, e.g.:

```python
i=rm.issue.get(1)

if hasattr(i, 'notes'):
    # do something

print getattr(i, 'notes', 'no notes, sorry') // 3rd arg is the default value is notes attr isn't avalable
```

These are 2 pythonic ways to work with attributes that may not always be available.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
