### ISSUE TITLE
RedmineCrm Helpdesk

### ISSUE THREAD

**Issue by urba1n** [maxtepkeev/python-redmine#116]
Do you plan to add support for redminecrm helpdesk plugin ?

**Comment by maxtepkeev** [comment]
Yes, I have plans to add support for all Redmine CRM plugins. No ETA though.

**Comment by cblakeweb** [comment]
Any updates on the support of CRM plugins?

From what you know about how plugins interface with the base redmine package, would modifying the REST API directly be a possible short term solution?  The plugins seems to create classes that belong to the issue class, however that data isn't natively built into REST.  If REST were modified, I would think that running a dir(issue) would return anything it found (assuming the fields aren't hardcoded in python-redmine).

This would be for the Agile CRM plugin to be able to obtain story points through REST.

**Comment by maxtepkeev** [comment]
I'm currently working on python-redmine v2 which will bring a lot of enhancements and new features, including CRM plugins support. I hope to prepare a release by the end of october or maybe a little bit earlier.

As to your suggestion about modifying REST API directly, I assume you are talking about modifying CRM plugins written in Ruby to expose their data not though separate api endpoints e.g. /helpdesk/* but through current standard endpoints like /issues/* - yes, that will work, because python-redmine doesn't hardcode attributes and all new attributes that will appear after such REST API modification will be available through python-redmine immediately.

**Comment by cblakeweb** [comment]
Thanks for the response!  Yes, I was talking about modifying the /issues/* endpoint as a temporary workaround until full CRM support is built into python-redmine.  I was hoping to expose the plugin class to the api object that does the mapping, then hopefully that field would return when issues object is obtained through python-redmine.

**Comment by cblakeweb** [comment]
Any updates on this integration?

**Comment by maxtepkeev** [comment]
Working on it right now, will be available in v2.0.0 which should be available somewhere in March.

**Comment by maxtepkeev** [comment]
I thought I'll share a little update on this one.

Unfortunately during the work on this issue I realised that it's not that easy to add support for this plugin, because it doesn't follow the usual design of other plugins/resources in Redmine. I mean of course I could add a quick'n'dirty support for it but that is not what I want to do.

I have ideas how I can restructure some parts of Python-Redmine to make implementing support for this kind of plugins easier, but because that will take some time and because I don't want to hold a 2.0.0 release anymore I decided to add support for this plugin in v2.1.0 instead of v2.0.0.

**Comment by sweh** [comment]
Any updates on this one?

**Comment by maxtepkeev** [comment]
@sweh no updates so far, the Helpdesk API hasn't been fixed, as stated in #204 we were waiting for the plugin developers to make a few fixes to make API consistent and usable but they didn't. We asked several times but received no response, so we just gave up on this one.

**Comment by sweh** [comment]
Yea, I noticed that. Is that a "its not working at all" or just a "the api is not consistent enough to get it right on our side" thing. Unfortunately, the Helpdesk public api documentation does not mention if its possible to add a contact to an issue. I mailed them earlier, so hopefully they'll tell me soon, but maybe you guys already know the api endpoint better and can help me out with e.g. a little curl statement. :-)

**Comment by maxtepkeev** [comment]
@sweh in general it's more of a "the api is not consistent enough to get it right on our side", but there's also a few bugs that bother us, for instance have a look what happens if you do multiple calls to create a ticket with the same params:

<img width="477" alt="2" src="https://user-images.githubusercontent.com/3032449/131671472-6dfb81f1-92fe-42e8-b22f-623bca51ed1d.png">

Regarding the question about adding a contact to a ticket, I think it's covered by the docs, have a look at https://www.redmineup.com/pages/help/helpdesk/rest-api-create-ticket. You have to add both issue and assign a contact to create a ticket.

**Comment by sweh** [comment]
> Regarding the question about adding a contact to a ticket, I think it's covered by the docs, have a look at https://www.redmineup.com/pages/help/helpdesk/rest-api-create-ticket. You have to add both issue and assign a contact to create a ticket.

Yea, I already tried that and thats working. But it does not help with existing tickets. I worry there is no API for that use case. :-(

**Comment by maxtepkeev** [comment]
@sweh oh I see what you mean, yes, afaik that case isn't covered by their API, if only they added it recently or will add it on your request.

**Comment by vihoa** [comment]
@maxtepkeev I'm wondering whether there is an update for the helpdesk?

**Comment by maxtepkeev** [comment]
Finally, Python-Redmine v2.4.0 (PRO edition) supports Helpdesk plugin.

**Comment by sweh** [comment]
Works like a charm. Thanks a lot!

**Comment by maxtepkeev** [comment]
@sweh Thanks for the feedback.

Helpdesk plugin API isn't perfect still, so let me know if you find anything missing or not working properly.
