### ISSUE TITLE
issue.project.identifier missing

### ISSUE THREAD

**Issue by dpocock** [maxtepkeev/python-redmine#123]
When I fetch a list of issues, I can access issue.project.id and some other attributes of the project, such as its name, but I can't access issue.project.identifier

Even if I do issue.project.refresh() the identifier is still missing.

**Comment by maxtepkeev** [comment]
As you said, there is no ``identifier`` available when you fetch a list of issues and try to access the project resource's identifier attribute of an individual issue. This is because Redmine itself doesn't send it to us via REST API and python-redmine can't do anything about it.

There is a ``refresh()`` method exactly for this situation, to re-request resource with all available attributes. The ``refresh()`` method currently returns a **new** refreshed object and not refreshes itself with new received attributes, I believe this is a source of your problem, you're expecting a refresh of a resource but it doesn't work this way.

I know this is not intuitive and this issue was already raised, so the new python-redmine 2.0 which is coming in the next few months will fix this behaviour.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
