### ISSUE TITLE
can't tell if issue is private

### ISSUE THREAD

**Issue by dpocock** [maxtepkeev/python-redmine#125]
Some issues are private in Redmine

When I do ```print vars(issue)``` I can't see any attribute indicating whether it is public or private.

**Comment by maxtepkeev** [comment]
If issue is private there will be a ``is_private`` attribute set to True, otherwise this attribute doesn't exist. Unfortunately this is how Redmine REST API works, to get around this you can use Python's ``getattr``, e.g. ``getattr(issue, 'is_private', False)``, which means, if is_private attr exists, return it's value, otherwise return False.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
