### ISSUE TITLE
Redmine assign_to_id set to string me but no assignee set.

### ISSUE THREAD

**Issue by Dark-Passenger** [maxtepkeev/python-redmine#133]
as described. no error either.

**Comment by maxtepkeev** [comment]
It should be ``assigned_to_id`` not ``assign_to_id``.

**Comment by Dark-Passenger** [comment]
oops my bad it was assigned_to_id. when giving string 'me' as value it sets nothing to assignee but with assignee id it sets the correct assignee.

**Comment by Dark-Passenger** [comment]
Oh wait my bad it seems it doesnt set assignee to api key user for issue creation when assigned_to_id is set to string me

**Comment by maxtepkeev** [comment]
I've tried and it doesn't work for me either. I've consulted Redmine REST API docs and came to the conclusion that it shouldn't work, have a look at [docs](http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Creating-an-issue), here it says "assigned_to_id - ID of the user to assign the issue to (currently no mechanism to assign by name)" (nothing about ``me`` though).

``Me`` does work when retrieving issues though [docs](http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Listing-issues) - "assigned_to_id: get issues which are assigned to the given user id. me can be used instead an ID to fetch all issues from the logged in user (via API key or HTTP auth)".

So, because python-redmine is just a client to a redmine, I can do nothing about about, you have to open a feature request at their forum for this.

**Comment by Dark-Passenger** [comment]
Yup realized that thanks for the help.

**Comment by fmonera** [comment]
Deleting the asignee is not working for me too:

self.currentIssue.assigned_to_id = None
self.currentIssue.save()

The asignee is unmodified.

**Comment by maxtepkeev** [comment]
@fmonera You should set it to an empty string, this way it works:

```python
self.currentIssue.assigned_to_id = ''
self.currentIssue.save()
```

Since it's becoming a popular question I will make it possible to set this one to ``None`` and ``0``  as well and it will be convereted to ``''`` automatically since that's what Redmine's JSON REST API is demanding for.
