### ISSUE TITLE
Some documentation for searches

### ISSUE THREAD

**Issue by vlegoff** [maxtepkeev/python-redmine#157]
Hello,

I saw in a previous (closed) issue that searches were implemented in PythonRedmine.  That's great!  But I wasn't able to find documentation associated with this particular topic.  I'm not afraid to look into the library code, but I couldn't find it either (probably didn't look well enough).  If you ever need help writing documentation, that's something I really enjoy doing.

**Comment by maxtepkeev** [comment]
Hi,

You're probably referring to https://github.com/maxtepkeev/python-redmine/issues/138#issuecomment-260201051. I don't know what else to add to this comment, because there is a link to the code and as I said it will be a part of 2.0.0 release which is just not released yet, that is why there is no docs available at the moment, so you have 2 options:

1) Wait until release
2) Use a code from [v2](https://github.com/maxtepkeev/python-redmine/tree/v2) branch and try it for yourself right now, but you'll have to explore the code a little bit to get the idea how to use new features, because as I said, docs for v2 will be ready only by the time of release.

I can't tell you the ETA for v2, I planned to release it by the end of October, but unfortunately a lot of things going on in my life right now, so I guess the release won't be ready until February or even March of 2017. Also if you decide to try v2 branch, keep in mind that this isn't stable right now, so I can't guarantee that everything will work properly.

Anyway thanks for suggesting your help with docs, I'll keep that in mind.

**Comment by vlegoff** [comment]
Hi,


Sorry, I had read the comment about V2 but I figured it was already 
out.  Didn't check.  No worries, take your time, I prefer to run on the 
stable version.  And perhaps Redmine 3.4 (with its long-expected REST 
API for files) will be released, but probably not before V2.  We'll see!

**Comment by maxtepkeev** [comment]
No problems! Yeah, 3.4 with Files API would be great. Even if it's not ready until v2 it will be easy to add support for it, because I did a lot of refactoring in v2, because it was written in 2014 and a lot has changed for these 2 years, basically this is the main reason why v2 takes so long to release.
