### ISSUE TITLE
When I don't have "assigned_to_id" attribute on the "issue" object and call the "save" method, a random assignee show up in the ticket occasionally.

### ISSUE THREAD

**Issue by szhang24** [maxtepkeev/python-redmine#163]
In some cases it's just blank. However sometimes it will show a random person as assignee. Not sure if someone else had the same problem before. So basically, I want the assignee to be Blank. Is there way to make sure that? Thank you!

**Comment by maxtepkeev** [comment]
Because you're asking this question, I guess the suggested solution to #162 worked for you. Please consider replying back and close the issue. This is not good to ask questions and keep silence after receiving a reply. Thanks.

No speaking about current question. This is very strange and I never heard about that happening to someone. It can't be a bug on python-redmine for sure. It's either your code that is doing that somehow (i.e. bug in your code) or bug in Redmine itself, which means you should ask on their support forum. You can also try to set assigned_to_id to None or '' or 0 and see if that works for you, but as I said it is very strange.

**Comment by szhang24** [comment]
Thank you for your reply!
