### ISSUE TITLE
How to use python-redmine with Flask-Login?

### ISSUE THREAD

**Issue by mengkheang** [maxtepkeev/python-redmine#168]
With Custom Resource and External Authentication

```python
from redmine.resources import User
from flask_login import UserMixin


class CustomUser(UserMixin, User):
    pass

```

```python
from redmine.exceptions import AuthError

username = 'john'    # username comes from the POST request on form submit
password = 'qwerty'  # password comes from the POST request on form submit

try:
    user = Redmine('https://redmine.url', username=username, password=password).auth()
except AuthError:
    raise Exception('Invalid login or password provided')
```

Can use utilize these two to make it work with Flask-Login?

**Comment by maxtepkeev** [comment]
Yes it is possible, but you need to write some code to do this. Python-Redmine provides you the auth mechanism to find out whether user used right login/password combination or not. But the integration with Flask or any other framework has to be written by yourself.

**Comment by mengkheang** [comment]
Can you provide some insight on how to implement it? I can't seem to figure it out.

**Comment by maxtepkeev** [comment]
I'm afraid not because this has nothing to do with Python-Redmine. Also I used Flask framework long time ago, so I had to go through all it's documentation, then through all Flask-Login documentation to figure it out. Please understand that I can't provide support for all the frameworks out there, that is why I made a basic functionality that can be integrated with every framework, but you have to write the code yourself. Maybe at some point in the future I will manage to find some time to write adapters for most popular frameworks like Flask, Django, Pyramid etc., but that won't happen soon, because I need to develop the library itself.

**Comment by mengkheang** [comment]
@maxtepkeev okay thank!
