### ISSUE TITLE
user.create doesn`t send email with information about creation of new account

### ISSUE THREAD

**Issue by fafnir1990** [maxtepkeev/python-redmine#177]
I would like to ask is that habit correct. Is it possible to set option which allow to send an account information to user?

Best regards

**Comment by maxtepkeev** [comment]
Yes, that behaviour is correct. Such functionality never existed in Python-Redmine because as far as I remember there was an option in Redmine itself to send emails to users after their account was created, though I never tried whether it applies to user accounts created via API.

Anyway, sending email may involve a lot of different small things here and there, so I don't thing this should be a part of Python-Redmine and you can easily implement it yourself in your code or if you want to encapsulate it into Python-Redmine, you can create a custom resource which inherits from User and use [post_create()](https://python-redmine.com/advanced/custom_resources.html#redminelib.resources.BaseResource.post_create) method to store your email sending code.

**Comment by fafnir1990** [comment]
Ok, thank you!
