### ISSUE TITLE
Uploading files with redmine.issue.update

### ISSUE THREAD

**Issue by FabioOrsi** [maxtepkeev/python-redmine#183]
Hello!

I've been trying to upload files to issues using the following call:

`redmine.issue.update(issue.id, uploads = [{"path" : stlpath, "filename" : str(id + ".stl"), "content_type" : "application/octet-stream"}])
`

It uploads and the files are displayed correctly on the browser, but when I download any of these files it comes without the filename and extension. If I upload through browser everything works perfectly.
I have also tried different MIME types without success.

The documentation for Attachments says:

> Some resources support adding attachments via it’s create/update methods, e.g. **Issue**, WikiPage.

And the documentation for Issues says:

> redmine.issue.update(resource_id, uploads = [{'path': '/absolute/path/to/file'}, ...

What am I doing wrong?

Thanks!

**Comment by DmitryKaramin** [comment]
Everything works nice.
I think that you should try 'filename': '{}.stl'.format(id) or 'filename': str(id)+'.doc' but not "filename" : str(id + ".stl")
with your "filename" you should receive:
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Unfortunately i don't have .stl file. I made a try with .txt and .doc files.

**Comment by FabioOrsi** [comment]
Tried your two suggestions without success. =(

I'm attaching an STL to test.

[cube.stl.zip](https://github.com/maxtepkeev/python-redmine/files/1265559/cube.stl.zip)

**Comment by DmitryKaramin** [comment]
Please check this http://demo.redminecrm.com/issues/607

**Comment by maxtepkeev** [comment]
@FabioOrsi What I suggest you to do is to try to upload a file against a demo.redmine.org or demo.redminecrm.com (2 public Redmine instances out there that have one of the latest versions installed) and see if the problem persists. If yes, then we can have a look at the Python-Redmine code and try to find out what can be wrong there, if the problem goes away, I would suggest to try to upgrade to the latest Redmine version, because that is most likely a bug in the Redmine itself or if you're using something in front of it, let's say nginx, that can be a configuration issue as well.

**Comment by FabioOrsi** [comment]
@maxtepkeev @DmitryKaramin I tried uploading the file to demo.redminecrm.com and it worked perfectly. I'll take a look at our redmine implementation and see what's causing this problem. Thanks a lot!
