### ISSUE TITLE
How can delete assignee of issue by rest api?

### ISSUE THREAD

**Issue by thanhpham310** [maxtepkeev/python-redmine#196]
Could you please help me, I try to delete assignee from an issue by following code, but assignee of issue is not deleted.
PUT /issues/10.xml
body content:
&lt;?xml version="1.0"?&gt;
&lt;issue&gt;
  &lt;assigned_to_id&gt;&lt;/assigned_to_id&gt;
&lt;/issue&gt;
Please show me the way that I can delete assignee of issue by rest api?

**Comment by maxtepkeev** [comment]
``redmine.issue.update(576, assigned_to_id='')``

**Comment by thanhpham310** [comment]
I try it:
1. Case1:
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;issue&gt;
    &lt;project_id&gt;40&lt;/project_id&gt;
    &lt;tracker_id&gt;4&lt;/tracker_id&gt;
    &lt;assigned_to_id&gt;''&lt;/assigned_to_id&gt;
&lt;/issue&gt;
--> But, the result:
&lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;errors type="array"&gt;&lt;error&gt;Assignee is invalid&lt;/error&gt;&lt;/errors&gt;
2. Case2
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;issue&gt;
    &lt;project_id&gt;40&lt;/project_id&gt;
    &lt;tracker_id&gt;4&lt;/tracker_id&gt;
    &lt;assigned_to_id&gt;''&lt;/assigned_to_id&gt;
&lt;/issue&gt;
-> But, assignee is not deleted.

**Comment by maxtepkeev** [comment]
@thanhpham310 This is a python-redmine issue tracker. Python-Redmine uses Redmine's JSON REST API and not a XML one, so this is not the right place to ask this type of questions. If you try to use python-redmine with the code example I gave to you, you will see that everything works.

The right place to ask why raw REST API calls don't work is the Redmine forum. I can't support Redmine since I didn't write it.

**Comment by thanhpham310** [comment]
I'm only creating an application to get, create, update and delete isssue by using rest api (http://www.redmine.org/projects/redmine/wiki/Rest_Issues).  But I can't update assignee of existed issue to blank.
Thanks you for your supporting!
