### ISSUE TITLE
Please stop vendoring requests

### ISSUE THREAD

**Issue by thomasgoirand** [maxtepkeev/python-redmine#200]
Hi,

It'd be nice if python-redmine was not vendoring requests. There's at this time no reason to do so. python-redmine itself is going to be used by other projects, and will probably be fetch by pip or other mechanism (ie: Debian package or whatever). In this type of situation, having a dependency is much nicer than a vendored library, and one more or less dependency to fetch with pip is not annoying at all.

On the opposite side, a vendored lib is potentially a security issue. There's been some security problems with requests in the past, as it's a lib that accesses the internet, it's very much possible it happens again. I don't think it's reasonable to tell "it's ok, we'll update it" while this may affect anyone using python-redmine, and these users may take time to upgrade too (ie: even with best security practice for upgrading on your side, it's still a problem).

Hoping this isn't annoying too much to read these lines and that I successfully convinced you.

**Comment by maxtepkeev** [comment]
Hi,

You're not the first, you're not the last. And the arguments against vendoring are always the same, nothing new really...

Have you read the [documentation](https://python-redmine.com/installation.html#dependencies) regarding vendoring requests, because it explains that we don't just simply vendoring it. It's a bit more complicated and the strategy is fully explained there.

**Comment by maxtepkeev** [comment]
We've stopped vendoring Requests since v2.2.0 due to the fact that Requests did the same with its own dependencies.
