### ISSUE TITLE
redminelib.exceptions.AuthError: Invalid authentication details

### ISSUE THREAD

**Issue by njduck** [maxtepkeev/python-redmine#224]
Redmine Version: 3.4.3.stable

### Settings
```
from redminelib import Redmine, engines, exceptions

REDMINE_URL             = 'http://192.168.1.100/'  
REDMINE_AUTH_KEY        = 'xxxxxxxxx' 

redmine = Redmine(REDMINE_URL, key=REDMINE_AUTH_KEY)
if redmine.auth():
    print('Auth Ok')
else:
    print("Auth Failed')
    exit()
```
### Success Cases
```
project = redmine.project.get(1)
print(project['name'])
```
### Falied Cases
```
projects = redmine.project.all()
for project in projects:
    pass
````
```
groups = redmine.group.all()
for group in groups:
    pass
````
```
group = redmine.group.get(1)
````
### Error
File "/home/ubuntu/.local/lib/python3.6/site-packages/redminelib/managers/base.py", line 83, in get
  return self.to_resource(self.redmine.engine.request('get', self.url, params=self.params)[self.container])
File "/home/ubuntu/.local/lib/python3.6/site-packages/redminelib/engines/base.py", line 76, in request
  return self.process_response(self.session.request(method, url, **kwargs))
File "/home/ubuntu/.local/lib/python3.6/site-packages/redminelib/engines/base.py", line 153, in process_response
  raise exceptions.AuthError
redminelib.exceptions.AuthError: Invalid authentication details

**Comment by maxtepkeev** [comment]
Hi @njduck 

That's not something I can help you with, the exception says it all. In your case some requests work because not all API endpoints require authentication, so I would check the following:

1) You've enabled REST API in the admin interface
2) You use key of an account that has admin privileges and the key is correct
3) You don't have any proxies in front of Redmine which, if configured incorrectly, can remove headers and do other magic which can influence on the authentication

Anyway you can check http://demo.redmineup.com (login/password is admin) and see that python-redmine works properly there.

**Comment by njduck** [comment]
> Hi @njduck
> 
> That's not something I can help you with, the exception says it all. In your case some requests work because not all API endpoints require authentication, so I would check the following:
> 
> 1. You've enabled REST API in the admin interface
> 2. You use key of an account that has admin privileges and the key is correct
> 3. You don't have any proxies in front of Redmine which, if configured incorrectly, can remove headers and do other magic which can influence on the authentication
> 
> Anyway you can check http://demo.redmineup.com (login/password is admin) and see that python-redmine works properly there.

Thansk for the reply.
I‘ve already enabled the REAT API in the admin interface
BTW,  your setting interface in Administration shows: 404 Not Found
:)

**Comment by maxtepkeev** [comment]
@njduck If you're talking about http://demo.redmineup.com that's not my website, but you're right http://demo.redmineup.com/settings gives you 404, I assume because admin of that website doesn't want someone to play with the settings, also there's no need to do that, everything is already set up correctly on that website.

**Comment by njduck** [comment]
Additional Information:
  number of projects: 1243
  number of groups: 105

**Comment by njduck** [comment]
> @njduck If you're talking about http://demo.redmineup.com that's not my website, but you're right http://demo.redmineup.com/settings gives you 404, I assume because admin of that website doesn't want someone to play with the settings, also there's no need to do that, everything is already set up correctly on that website.

I tried above failed cases on http://demo.redmineup.com.
Works fine.

Is there any limits in python-redmine?

**Comment by maxtepkeev** [comment]
No, python-redmine is just an API client, it's Redmine's API that replies with "Invalid authentication details" and python-redmine just translates the reply to you. So as I adviced before, check your Redmine configuration/credentials used.

**Comment by njduck** [comment]
After disabled plugin 'favorite projects',
redmine.project.all() works fine~~~
redmine.group.all() still not work.
This should be some plug-in's problem.

This issuse could be closed
