### ISSUE TITLE
Update custom_field

### ISSUE THREAD

**Issue by maxdeff** [maxtepkeev/python-redmine#228]
Hi,
Thank you for the great job.
I know the documentation says Redmine does not support updating the possible values of a custom_field (https://python-redmine.com/resources/custom_field.html). However, it seems to be possible in Ruby, so I wonder whether there is a workaround with Python.

(I briefly explain what I want to do. There are two projects, "Purchases" and "Funding sources". To pass an order, a user creates an issue within the project "Purchases", and choose a "Funding source" as a custom_field (a list of possible values).
When new funding is secured, any user can create a new issue within the project "Funding sources", and ideally, a script would extract the subject of this new issue (the name of the new funding source), and use it to automatically add the new funding source to the list of possible values of the custom_field in "Purchases". Moreover, funding sources have starting/ending dates, so conditions will be added to the automatic integration of funding sources.)

**Comment by giladste** [comment]
Hi Max,
Thank you for your reply.
I am not familiar with ruby at all. Moreover I'm new to python as well as
Redmine.
I didn't understand your workaround.
Can we skype on the solution?
My username is giladpac
Thanks

**Comment by maxdeff** [comment]
Hi Giladste,
I don't have a workaround yet! That's the reason why I posted the question here.
Max

**Comment by maxtepkeev** [comment]
Hi @maxdeff 

Python-Redmine relies heavily on Redmine's REST API and since it doesn't have an endpoint for creating/updating new custom fields what you're asking for is unfortunately not possible. By workaround in Ruby you probably mean directly interfacing Redmine's DB or directly using Redmine's functionality. You can actually do something like this in Python, but that has nothing to do with Python-Redmine as it's purely an API client.

**Comment by maxdeff** [comment]
Hi @maxtepkeev 
Thanks for your answer. I'll learn Ruby then.
