### ISSUE TITLE
How to get user.status attribute?

### ISSUE THREAD

**Issue by plantusd** [maxtepkeev/python-redmine#235]
![image](https://user-images.githubusercontent.com/44056339/64818719-4bdbbe80-d5b5-11e9-80fc-a8298088f2b5.png)
![image](https://user-images.githubusercontent.com/44056339/64818748-62821580-d5b5-11e9-8e5f-1e39efa8bc0c.png)
 output:

![image](https://user-images.githubusercontent.com/44056339/64818774-74fc4f00-d5b5-11e9-9a57-3964614d08f1.png)

Thanks a lot!

**Comment by maxtepkeev** [comment]
This attribute is only available when you request a specific user, i.e. ``self.conn.user.get(1)``. I know this is very inconvenient, but this is how Redmine's API works. You can go to their forum and fill a feature request.

The other option is to use ``filter()`` instead of ``all(), because you can filter users with specific statuses and then merge them all together knowing their status. That will be way less requests to the API.
