### ISSUE TITLE
List of children project

### ISSUE THREAD

**Issue by zipon7** [maxtepkeev/python-redmine#240]
Is there a way to list all children projects in parent project?

**Comment by maxtepkeev** [comment]
``issue.children`` attribute is available if an issue has children

**Comment by zipon7** [comment]
I have projects that are assigned to parent project:
-**Parent project**
--**Child project 1**
--- Issue 1
--- Issue 2
--**Child project 2**
---Issue 1
I want to see all children projects for "Parent project"

**Comment by maxtepkeev** [comment]
Oh sorry, you were asking about projects and not issues. I'm afraid there's no easy way there, because Redmine's API doesn't provide us with the same ``children`` attribute as for issues.

The only way to go is to retrieve all projects and then iterate over them in a loop checking if the ``parent`` attribute exists and creating a hierarchy by yourself.

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
