### ISSUE TITLE
ResourceSet.update() missing custom field name return value

### ISSUE THREAD

**Issue by brycesauce** [maxtepkeev/python-redmine#289]
I've noticed when using the `update()` function on a `ResourceSet` object containing Issues that when updated a custom field value, the new `ResourceSet` object returned by the `update()` function does not return the updated custom field name unless the custom field name is specified. The docs say only the custom field ID needs to be used, and while technically this is correct and still works, the update() function in particular doesn't return the custom field name.

Example with passing the following parameters to the update() function on a ResourceSet object of Issues:
`{
        'custom_fields': [
            {
                'id': 167,
                'value': 0,
            }
        ]
    }
`
returns:
`{
        'custom_fields': [
            {
                'id': 167,
                'value': 0,
            }
        ]
    }
`
but doing a fresh filter query to get the same issue(s) shows the correct return:
`{
        'custom_fields': [
            {
                'id': 167,
                'name': "Sample Field Name",
                'value': 0,
            }
        ]
    }
`

**Comment by maxtepkeev** [comment]
Hi @brycesauce 

Apologies for such a late reply.

I understand your pain, but this is due to how Redmine's REST API, which Python-Redmine is using, works. All `update` operations return just `True` or raise an Exception because this is exactly what Redmine's REST API does. So when you're updating each issue in a resource set with `{ 'custom_fields': [ { 'id': 167, 'value': 0, } ] }`, you'll have exactly the same value in each issue's custom fields resource set.

To overcome this frustration Python-Redmine provides you with a shortcut for such cases which is called a `refresh()` and is documented [here](https://python-redmine.com/introduction.html#refresh). Basically it's a method which is available for any resource and is worth usable in a case when you have or Redmine gave you just id + whatever, but you need all attributes of the resource.

But since a `refresh()` is doing a separate request to Redmine for each resource it's been called on, and I assume you have lots of custom fields and/or issues, in your case I would just try to use { 'custom_fields': [ { 'id': 167, 'name': "Sample Field Name", 'value': 0, } ] } plus other attributes together with the `name` when setting a custom field in an `update()`, I'm not sure if Redmine likes it or not, but you could try and if that works, that would be the best approach if you need to work with those attributes in your code later after update operation is done
