### ISSUE TITLE
user_id not supported in time

### ISSUE THREAD

**Issue by smehrbrodt** [maxtepkeev/python-redmine#298]
According to https://www.redmine.org/projects/redmine/wiki/Rest_TimeEntries , the property user_id is supported:
> "user id to be specified in need of posting time on behalf of another user"

But python-redmine does not support this property. Please add support for this. 
It's useful for importing times from another source.

**Comment by maxtepkeev** [comment]
@smehrbrodt Hi, it's actually supported because we don't hardcode any param names in the code, so even if you see that there's no info in the Python-Redmine docs, but there's info in the Redmine docs - you can safely use it in Python-Redmine too most of the time. But thanks for raising this issue anyway, I've updated the Python-Redmine docs regarding user_id.
