### ISSUE TITLE
limit parameter not working

### ISSUE THREAD

**Issue by KopylovVadik** [maxtepkeev/python-redmine#300]
hi
I'm trying to get projects and their users.
it works with concrete id
```
        project = [values for values in self.entity.project_membership.filter(project_id=1037).values()]

```
but it does not work if you try to get several projects at once through the parameter limt like the picture below:
<img width="817" alt="Снимок экрана 2022-05-30 в 14 21 21" src="https://user-images.githubusercontent.com/21989007/170982050-d2b2866a-41f9-4a5f-b5e4-3c9e46aa7db4.png">

**Comment by maxtepkeev** [comment]
Hi, sorry that it took me so long to reply, basically it's not working because it's not supported by the underlying Redmine REST API, if you check the docs (https://python-redmine.com/resources/project_membership.html#all) you'll see that it says that `all()` method isn't supported, so in order to do what you want you'll have to get all project id's using `redmine.project.all()` and then with every project_id you need to make a request using `redmine.project_membership.filter(project_id=X)`. That's the only way as of now.
