### ISSUE TITLE
Project's parent attribute doesn't exist if project is retrieved from a group membership

### ISSUE THREAD

**Issue by matletix** [maxtepkeev/python-redmine#303]
Here is a minimal working example. I have a redmine group "My Redmine Group" associated with the 2 following projects : 

Root Project (id=1)
└── Subproject (id=4)

```python
########## Explicitly get project with id=4 and get its parent : working
>>> p = redmine.project.get(4)
>>> p
<redminelib.resources.Project #4 "Subproject">
>>> p.id
4
>>> p.parent
<redminelib.resources.Project #1 "Root Project">

########## Get project through group membership and get its parent : not working
>>> group
<redminelib.resources.Group #7 "My Redmine Group">

# Fetch the projects associated to the group via the "membership" attribute
>>> projects = [membership.project for membership in group.memberships]
>>> projects
[<redminelib.resources.Project #1 "Root Project">, <redminelib.resources.Project #4 "Subproject">]

# Get the parent of project with id=4
>>> projects[1]
<redminelib.resources.Project #4 "Subproject">
>>> projects[1].id
4
>>> projects[1].parent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/redminelib/resources/base.py", line 197, in __getattr__
    raise exceptions.ResourceAttrError
redminelib.exceptions.ResourceAttrError: Resource doesn't have the requested attribute

# Expected behaviour : return <redminelib.resources.Project #1 "Root Project">
```
Versions:
- Python: 3.9
- python-redmine: 2.3.0

**Comment by maxtepkeev** [comment]
Hi @matletix 

Python-Redmine uses Redmine's REST API to communicate with Redmine and unfortunately Redmine's REST API is build in a way that it doesn't provide you with all the data about a resource if it's accessed via associated endpoints, it only gives you a minimum like id/name, so that if you really need to retrieve all the attributes of an associated resource you could do that yourself knowing this minimum. Python-Redmine provides you with a shortcut for such cases which is called a `refresh()` and is documented [here](https://python-redmine.com/introduction.html#refresh). Basically it's a method which is available for any resource and is worth usable for a case like you described when Redmine gave you just id/name, but you need a parent id or any other project's attribute, so you could have done something like this:

```python
>>> projects = [membership.project for membership in group.memberships]
>>> projects
[<redminelib.resources.Project #1 "Root Project">, <redminelib.resources.Project #4 "Subproject">]

# Get the parent of project with id=4
>>> projects[1].refresh()
>>> projects[1].parent  # this time it will work if a project really has a parent project
```

but keep in mind that `refresh()` makes a separate request to Redmine every time it's called, so it can take a while if you have lots of projects.
