### ISSUE TITLE
issues relation on user is misleading

### ISSUE THREAD

**Issue by xrisk** [maxtepkeev/python-redmine#317]
`redmine.user.get(...).issues` searches on the `assigned_to` field which might not be what the user expects.

**Comment by maxtepkeev** [comment]
@xrisk Yep, `user.issues` currently returns issues user has been assigned to, and as far as I understand you were expecting it to return issues that user has authored, am I right ?

Both scenarios are perfectly valid and I've chosen the first one for `user.issues` just because it's the most common one, but you're right that it can be confusing, so we can probably come up with 2 relations here like:

1) `redmine.user.get(...).issues_authored`
2) `redmine.user.get(...).issues_assigned`

Just maybe we need to think of more short and clear relation names here...

**Comment by misilot** [comment]
Would something like the following make sense?

* `redmine.user.get(...).issues.assigned`
* `redmine.user.get(...).issues.reporter`

**Comment by xrisk** [comment]
@misilot I’m not very conversant with the Django ORM, but as far as I understand, `.issues` should be a relation from users -> issues. The question is, should that relation be on the basis of author, or assignee? 

`issues.assigned` or `issues.reporter` doesn’t make sense to me, as those are not relations on `issues`.

**Comment by maxtepkeev** [comment]
I'm with @xrisk here, it should be a direct relation like I describe above, actually @xrisk could you please tell me if names like I mentioned make sense to you or you would prefer some other names or solution to the problem ?

**Comment by xrisk** [comment]
Yes, those names do sound good. But I did find that the redmine issues api doesn’t actually have a filter for authored_by (https://www.redmine.org/projects/redmine/wiki/Rest_Issues). I had to directly query the database when I needed to do this.

**Comment by maxtepkeev** [comment]
@xrisk Thanks, actually it does, you need to use `author_id` for that, so we shouldn't have any problems with implementing this feature, it's just that the page you mentioned doesn't have all possible filters Redmine support.

**Comment by maxtepkeev** [comment]
Fixed iin b595d0bb20b9eee86f16a29562b1c636c689dcde
