### ISSUE TITLE
Bug: User does not return status

### ISSUE THREAD

**Issue by misilot** [maxtepkeev/python-redmine#326]
The User resource does not return the users status of Locked, Registered, or Active (or the numeric values)

**Comment by maxtepkeev** [comment]
It actually does, if you do `redmine.user.get(X)` where X id the user id, you'll get a numeric value in a `status` property. But if you do `redmine.user.all()` or `redmine.user.filter()` you won't have this `status` property because Redmine API works liike this and only returns this property when you access a specific user via API, so it's their bug and not ours.

**Comment by misilot** [comment]
Thanks! I submitted a ticket upstream https://www.redmine.org/issues/38948

**Comment by maxtepkeev** [comment]
@misilot Thanks!
