### ISSUE TITLE
ResourceNoFieldsProvidedError when saving a new time_entry

### ISSUE THREAD

**Issue by brunetton** [maxtepkeev/python-redmine#70]
Hi, 

I'm using python-redmine for a new version of https://github.com/brunetton/redminetimesync script.
But I've got a problem while creating a TimeEntry :

```python
from redmine import Redmine
redmine = Redmine('http://localhost:3000', key='xxxxxxxxxxxxxxxxxxxxxx')

from datetime import datetime
time_entry = redmine.time_entry.create(
    spent_on=datetime.now(),
    issue_id=1,
    hours=1,
    activity_id=9,
    comments=None
)
time_entry.save()
```

I get :

    ResourceNoFieldsProvidedError             Traceback (most recent call last)
    <ipython-input-12-f9f9839f22d8> in <module>()
         10     comments=None
         11 )
    ---> 12 time_entry.save()
    
    /usr/local/lib/python2.7/dist-packages/redmine/resources.py in save(self)
        247         if not self.is_new():
        248             self.pre_update()
    --> 249             self.manager.update(self.internal_id, **self._changes)
        250             self._attributes['updated_on'] = datetime.utcnow().strftime(self.manager.redmine.datetime_format)
        251             self.post_update()
    
    /usr/local/lib/python2.7/dist-packages/redmine/managers.py in update(self, resource_id, **fields)
        200 
        201         if not fields:
    --> 202             raise ResourceNoFieldsProvidedError
        203 
        204         for index, upload in enumerate(fields.get('uploads', [])):
    
    ResourceNoFieldsProvidedError: Resource needs some fields to be set to be created/updated

Maybe I missed something ?

Thanks for help !

**Comment by brunetton** [comment]
I can observe that the time entry is correctly created in Redmine server side, so I suppose that error is not a big deal to fix ?

**Comment by brunetton** [comment]
Ok, I re-read the doc and got it : create() does.

Sorry, my fault :s 

Shame on me !

**Comment by maxtepkeev** [comment]
Hi Bruno,

False alarm, nothing to fix here on the python-redmine side.

You're getting this error because of the ``time_entry.save()`` call which is not needed, because ``redmine.time_entry.create()`` is a self-sufficient method which creates and returns created resource in one step, i.e, when you do:

```python
time_entry = redmine.time_entry.create(
    spent_on=datetime.now(),
    issue_id=1,
    hours=1,
    activity_id=9,
    comments=None
)
```

python-redmine calls Redmine API, creates the time entry resource and then you get the created resource object in time_entry variable. After that when you do ``time_entry.save()`` python-redmine throws the exception that no fields were set for creating/updating the resource which is exactly the truth.

``.save()`` method should be used when you're creating/updating resource in several steps, e.g.:

```python
time_entry = redmine.time_entry.new()
time_entry.spent_on=datetime.now()
time_entry.issue_id=1,
time_entry.hours=1,
time_entry.activity_id=9,
time_entry.comments=None
time_entry.save()
```

**Comment by brunetton** [comment]
Thanks for this really complete response.
I hope it'll be usefull to somebody else, maybe.
