### ISSUE TITLE
User object is missing 'login'

### ISSUE THREAD

**Issue by kopf** [maxtepkeev/python-redmine#73]
It would be useful to be able to get the username of a user from the `User` object.

**Comment by maxtepkeev** [comment]
It's there, see:
```python
>>> user = redmine.user.get('current')
>>> dir(user) 
['api_key',
 'contacts',
 'created_on',
 'custom_fields',
 'deals',
 'firstname',
 'groups',
 'id',
 'issues',
 'last_login_on',
 'lastname',
 'login',
 'mail',
 'memberships',
 'status',
 'time_entries']

>>> user.login
'm.tepkeev'
```

Some suggestions:
1) Check raw redmine response via http://you-redmine-server/users/user_id.json
2) Be sure you're using Redmine API via account with admin rights

**Comment by kopf** [comment]
Ah! Sorry! 

I was trying to get the login name of another user using python-redmine, and when I tested it in the browser against the rest api, I stupidly queried it with my own user id. So, I simply need to be querying it with admin rights. 

Thanks for the quick response and apologies for getting it wrong!

**Comment by maxtepkeev** [comment]
No problems. I believe this can be closed.

**Comment by kopf** [comment]
I'm afraid I might've spoken too soon. When I make a request by hand, using my admin api key, I get:

````
>>> import requests
>>> 'login' in requests.get('http://redmine/users/47.json', headers={'X-Redmine-API-Key': 'MY_API_KEY'}).json()['user']
True
````

When I do it using python-redmine (definitely also using the admin api key!):

````
>>> redmine = Redmine(REDMINE['url'], key=REDMINE['key'])
>>> proj = redmine.project.get('nbrsf')
>>> x = proj.wiki_pages[:5]
>>> dir(x[0].author)
['contacts', 'deals', 'groups', u'id', 'issues', 'memberships', u'name', 'time_entries']
````

**Comment by maxtepkeev** [comment]
Yes, everything works as expected.

In your first case you are requesting the User API endpoint which provides you with login attribute.
In your second case you are requesting a project, then wiki pages of the project, and then author of the first wiki page which is NOT the same as requesting just the user.

Python-Redmine returns you the exact information returned by the Redmine itself, and in your second case Redmine doesn't return you the full information about the user. But python-redmine provides you with the way to fix this Redmine behaviour, just do this:

```python
dir(x[0].author.refresh())
```

refresh() will request all the rest info about the user from Redmine, including the desired login attribute.

**Comment by kopf** [comment]
Aha ok. I notice that `.refresh()` returns an object instead of updating the `author` attribute of the wiki_page object. This is a little unintuitive.

Would it be an idea to update this in place, returning `None` from `.refresh()` instead?

**Comment by maxtepkeev** [comment]
Good idea, probably a parameter should be added to ``refresh()`` not to brake existing code.

I'll put that on my TODO list.

**Comment by kopf** [comment]
And I just noticed, the return value from `refresh()` is missing the attribute `name` (which I guess `python-redmine` stitches together itself), so I guess it shouldn't be a simple case of overwriting the object with the new one, but instead adding the missing data.

**Comment by maxtepkeev** [comment]
``name`` is missing because when you do a ``refresh()`` it is substituted by ``firstname`` and ``lastname``, I could add a ``name`` attribute for the sake of consistency.

**Comment by capiscuas** [comment]
Hi, i just encountered the same Redmine(not python-redmine) limitation about not having 'login' attribute after a time_entries request. I have a question Is user.refresh() triggering a new GET request or it's storing it in some sort of user object cache?

If am asking this because my app is generating a dictionary from all the redmine users at the beggining and I think it would be faster if I just take the login attribute from my dictionary based on the user id from memory?

**Comment by maxtepkeev** [comment]
Hi @capiscuas 

``refresh()`` method on the resource object is making a new GET request to get all the possible information about a resource from the Redmine. It can't have any kind of cache since to have this cache Python-Redmine would still need to make a request at some point. If we take a user resource as an example it will need to make one request per user since login attribute isn't available if you request all user at once.

If you already have a dict in memory with all the user attributes, it is definitely better to take the needed data from it than using a ``refresh()`` method.
