### ISSUE TITLE
How to get wiki pages versions

### ISSUE THREAD

**Issue by vmora** [maxtepkeev/python-redmine#86]
Hi,

I'm trying to get different versions of wiki pages. If

    myproject.wiki_pages.get(u'PageName')

works, I would expect, for version 17 of the page:

    myproject.wiki_pages.get(u'PageName/17')

but that doesn't work.

Any idea ?

Thanks.

**Comment by maxtepkeev** [comment]
Hi,

It's all there in the [docs](http://python-redmine.readthedocs.org/resources/wiki_page.html#get):

```python
myproject.wiki_pages.get(u'PageName', version=17)
```

**Comment by vmora** [comment]
I had already tried:

    myproject.wiki_pages.get(u'PageName', version=17)
    -> get() got an unexpected keyword argument 'version'

But the version in the doc:

    redmine.wiki_page.get('PageName', project_id='myProjectId', version=12)

works. Thanks a lot for the pointer.

**Comment by maxtepkeev** [comment]
Ah, now I get it. Sorry I was inattentive.

You are correct, the 

```python
myproject.wiki_pages.get(u'PageName', version=17)
```
won't work, because in this case ``wiki_pages`` is a ResourceSet object of the Project Resource object and it's ``get`` method has no idea about the version keyword argument, because it's just a helper to get the needed Resource from a ResourceSet by id. So one way of solving the problem is like this:

```python
for wiki_page in myproject.wiki_pages:
    version = wiki_page.refresh(version=17)
    # do something with the version
```

``refresh`` method is available on all resources and is very useful when you need to re-request something from Redmine which is not available by default (like another version of the wiki page).

The other way you already know, as stated in the docs it is:

```python
redmine.wiki_page.get('PageName', project_id='myProjectId', version=12)
```

In this case you are calling the ``get`` method on the ResourceManager object which requests data directly from Redmine and that is why that works.

Hope that helps.

**Comment by vmora** [comment]
Helps a lot, thanks.
