### ISSUE TITLE
ImportError: cannot import name Redmine - Installed on FreeBSD 10.1

### ISSUE THREAD

**Issue by laurentiuspurba** [maxtepkeev/python-redmine#89]
Hello all,

I just installed this module using pip and created a test script for using this library, but for some reason, I got 'ImportError: cannot import name Redmine' error message.

python version: **2.7.9**
FreeBSD: **10.1**

I appreciate any helps or pointers that you'll give me.
-Laurent

Below is my test script:
> #!/usr/bin/env python

> import sys
> from redmine import Redmine

> #redmine = Redmine('http://MYREDMINE.com', username='MYUSER', password='MYPASSWORD')
> #project = redimine.project.get('PROJECT1')

> #print "project id is " + str(project.id)

> print "Hello from python"

**Comment by maxtepkeev** [comment]
Hi Laurent,

Your error isn't connected with python-redmine, you're just having problems with relative imports, probably because your script is named redmine.py or it is defined in python module named redmine or you have some other module named redmine in your system.

To fix the error either rename your script/module to something that isn't called redmine or put this

```python
from __future__ import absolute_import
```

before ``import sys``

That should help.

**Comment by laurentiuspurba** [comment]
Hello Max,

Thanks for your prompt response.

I did rename the file from redmine.py to test.py, but the result is still the same. The other option that you suggested, by putting
```python
from __future__ import absolute_import
```
before <pre>import sys</pre> but again, the result is still the same.

Any idea?

Thanks!
-Laurent

**Comment by maxtepkeev** [comment]
Be sure to remove all *.pyc files also. If that doesn't help check that python interpreter that you're using, i.e. ``#!/usr/bin/env python``, is the same that was used during ``pip install`` procedure. It is very possible that they differ that is why you're getting this error.

**Comment by laurentiuspurba** [comment]
Removing all *.pyc does not help it either.

Btw, how do I know if I am using the same python interpreter on my script and pip install.

My python and pip version is as follows:

<pre>
johndoe@johndoe:python$ python --version
Python 2.7.9
johndoe@gitrepo:python$ pip --version
pip 6.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
johndoe@johndoe:python$ 
</pre>

**Comment by maxtepkeev** [comment]
Can you please show me the output of

1)
```python
/usr/bin/env python -c "import site; print site.getsitepackages()"
```
2)
```python
/usr/bin/env python -c "import sys; print sys.executable"
```
3)
```python
python -c "import site; print site.getsitepackages()"
```
4)
```python
python -c "import sys; print sys.executable"
```
5)
```bash
pip list
```

**Comment by laurentiuspurba** [comment]
```python
/usr/bin/env python -c "import site; print site.getsitepackages()"
```
Output:
<pre>
['/usr/local/lib/python2.7/site-packages', '/usr/local/lib/site-python']
</pre>

```python
/usr/bin/env python -c "import sys; print sys.executable"
```
Output:
<pre>
/usr/local/bin/python
</pre>

```python
python -c "import site; print site.getsitepackages()"
```
Output:
<pre>
['/usr/local/lib/python2.7/site-packages', '/usr/local/lib/site-python']
</pre>

```python
python -c "import sys; print sys.executable"
```
Output:
<pre>
/usr/local/bin/python
</pre>

<pre>
pip list
</pre>

Output:
<pre>
Babel (1.3)
docutils (0.12)
Jinja2 (2.7.3)
MarkupSafe (0.23)
pip (6.1.1)
Pygments (2.0.2)
python-redmine (1.1.1)
pytz (2014.10)
requests (2.7.0)
setuptools (5.5.1)
Sphinx (1.2.3)
</pre>

**Comment by maxtepkeev** [comment]
Hmm, everything seems to be ok, very strange... Can you please also show me the complete stack trace of the error, i.e. not only ``ImportError: cannot import name Redmine`` but the full stack trace.

**Comment by maxtepkeev** [comment]
And also, to be sure, do you have the ``redmine`` folder under /usr/local/lib/python2.7/site-packages ?

**Comment by laurentiuspurba** [comment]
Full stack trace:
<pre>
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    from redmine import Redmine
  File "/home/lpurba/latih/python/redmine.py", line 8, in <module>
    from redmine import Redmine
ImportError: cannot import name Redmine
</pre>

My test.py
```python
#!/usr/bin/env python

#from __future__ import absolute_import

import sys
from redmine import Redmine

print "Hello from python"
```

I have redmine directory under /usr/local/lib/python2.7/site-packages.
<pre>
johndoe@johndoe:python$ ls -l /usr/local/lib/python2.7/site-packages/        
total 409
drwxr-xr-x   2 root  wheel       9 May  7 15:25 Babel-1.3-py2.7.egg-info
drwxr-xr-x   2 root  wheel       9 May  7 15:25 Jinja2-2.7.3-py2.7.egg-info
drwxr-xr-x   2 root  wheel       7 May  7 15:25 MarkupSafe-0.23-py2.7.egg-info
drwxr-xr-x   2 root  wheel       8 May  7 15:26 Pygments-2.0.2-py2.7.egg-info
-rw-r--r--   1 root  wheel     119 May  5 19:14 README
drwxr-xr-x   2 root  wheel       9 May  7 15:26 Sphinx-1.2.3-py2.7.egg-info
drwxr-xr-x   2 root  wheel       8 May  5 19:14 _markerlib
-rw-r--r--   1 root  wheel    8429 May  5 21:16 asciidocapi.py
drwxr-xr-x   5 root  wheel      33 May  7 15:25 babel
drwxr-xr-x   8 root  wheel      32 May  7 15:26 docutils
drwxr-xr-x   2 root  wheel       6 May  7 15:26 docutils-0.12-py2.7.egg-info
-rw-r--r--   1 root  wheel     185 May 12 20:17 easy-install.pth
-rw-r--r--   1 root  wheel     185 May  5 19:14 easy-install.pth.dist
-rw-r--r--   1 root  wheel     126 Jun 29  2014 easy_install.py
-rw-r--r--   1 root  wheel     321 May  5 19:14 easy_install.pyc
-rw-r--r--   1 root  wheel     321 May  5 19:14 easy_install.pyo
drwxr-xr-x   3 root  wheel      72 May  7 15:25 jinja2
drwxr-xr-x   2 root  wheel      19 May  7 15:25 markupsafe
drwxr-xr-x  10 root  wheel      46 May  8 20:29 pip
drwxr-xr-x   2 root  wheel      10 May  8 20:29 pip-6.1.1-py2.7.egg-info
-rw-r--r--   1 root  wheel  101340 Aug 10  2014 pkg_resources.py
-rw-r--r--   1 root  wheel  109882 May  5 19:14 pkg_resources.pyc
-rw-r--r--   1 root  wheel  109817 May  5 19:14 pkg_resources.pyo
drwxr-xr-x   6 root  wheel      51 May  7 15:26 pygments
drwxr-xr-x   2 root  wheel       9 May 12 20:17 python_redmine-1.1.1-py2.7.egg-info
drwxr-xr-x   3 root  wheel      21 May  7 15:25 pytz
drwxr-xr-x   2 root  wheel       7 May  7 15:25 pytz-2014.10-py2.7.egg-info
drwxr-xr-x   2 root  wheel      16 May 12 20:17 redmine
drwxr-xr-x   3 root  wheel      32 May  8 21:11 requests
drwxr-xr-x   2 root  wheel       8 May  8 21:11 requests-2.7.0.dist-info
drwxr-xr-x   4 root  wheel      57 May  5 19:14 setuptools
drwxr-xr-x   2 root  wheel       9 May  5 19:14 setuptools-5.5.1-py2.7.egg-info
drwxr-xr-x  14 root  wheel      68 May  7 15:26 sphinx
drwxr-xr-x   2 root  wheel      20 May  6 21:37 xcbgen
</pre>

**Comment by maxtepkeev** [comment]
Looking at your stack trace:

```
Traceback (most recent call last):
  File "./test.py", line 6, in 
    from redmine import Redmine
  File "/home/lpurba/latih/python/redmine.py", line 8, in 
    from redmine import Redmine
ImportError: cannot import name Redmine
```

I have a feeling that when you do ``from redmine import Redmine`` it tries to import from /home/lpurba/latih/python/redmine.py and fails. Do you know what is this script doing ? If you have access to it try to rename it and see if it helps.

**Comment by maxtepkeev** [comment]
Also show me the output of ``python -c "import sys; print sys.path"``

**Comment by laurentiuspurba** [comment]
I deleted redmine.py in my directory and it's working now. Thanks for your help.

Other question is, does python-redmine support https also?

I tried the following code, but got different error message.
```python
#!/usr/bin/env python

import sys
from redmine import Redmine


redmine = Redmine('https://MYREDMINE.com', username='johndoe', password='johndoe', requests={'verify': False})
project = redmine.project.get('MYPROJECT')

print "project id is " + str(project.id)

print "Hello from python"
```

Stack trace:
<pre>
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "test-bak.py", line 13, in <module>
    project = redmine.project.get('MRMPlus')
  File "/usr/local/lib/python2.7/site-packages/redmine/managers.py", line 127, in get
    return self.resource_class(self, self.retrieve()[0])
  File "/usr/local/lib/python2.7/site-packages/redmine/managers.py", line 68, in retrieve
    raise ResourceNotFoundError
redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist
</pre>

**Comment by maxtepkeev** [comment]
Good, I just want to explain why it's working now and wasn't working before. If you execute ``python -c "import sys; print sys.path"`` you'll get a list of several directories on your system where Python is searching for a module when you do ``import modulename`` or ``from modulename import X``, the search is made from left to right. I believe that ``/home/lpurba/latih/python`` directory is listed before the ``/usr/local/lib/python2.7/site-packages``. So, when you do ``from redmine import Redmine`` and Python's import system starts it's search for a ``redmine`` module it stops when it founds ``/home/lpurba/latih/python/redmine.py`` and returns it to you but that is not the module that you were actually looking for. So the basic idea is that you shouldn't have modules/packages with similar names in your system. This is not a python-redmine's fault, this is how the Python's import system works and there is nothing what I can do here. We just have to keep that in mind.

As for your second question, yes, python-redmine supports ``https``, the warning that you get, i.e. ``InsecureRequestWarning`` comes from the fact that you're using the ``requests={'verify': False}``. I believe you're using this because you have a self-signed certificate on your Redmine server, if you want to disable this warning you can find how to do that [here](https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning). As to the exception you're getting, i.e. ``redmine.exceptions.ResourceNotFoundError``, it is raised when your Redmine server returns a 404 error. Can you access your project through a web browser via the ``https://MYREDMINE.com/projects/MYPROJECT`` ? I believe that you'll get a 404 error because that is what is returned by your Redmine server to python-redmine. Be sure to provide a valid project identificator.

Let me know if it still doesn't work and we'll continue to investigate the reasons.

**Comment by laurentiuspurba** [comment]
Sorry for late response.

Max, thank you so much for all your help. Everything now works as expected.

Awesome!!!

**Comment by maxtepkeev** [comment]
You're welcome.
